name: build
on: [push, pull_request]

jobs:
  build:
    name: Build Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: mkdir build
    - name: Configuration
      run: cmake -DPD_MULTI=ON -DPD_UTILS=OFF -DMSVC_STATIC_RUNTIME=ON ..
      working-directory: ./build
    - name: Build
      run: cmake --build . --target libpdstatic
      working-directory: ./build
